name: Storybook Preview

on:
  push:

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: '9'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build-storybook

      - uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
          if-no-files-found: error
